require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space